### ISSUE TITLE
Error when parsing interface number in hardware ID

### ISSUE THREAD

**Issue by JomerDev** [kevinmehall/nusb#38]
I got an error while using probe-rs which uses nusb where nusb can't parse an interface number in a hardware ID.
While probe-rs is still working with this error as the device that is causing the error is not the one I want to use it's still noisy since every time I run probe-rs I now get this error multiple times in the log.

A full log with RUST_LOG="trace": [here](https://gist.github.com/JomerDev/95f9bb6fdcdc252c0a6a0d64fc069b7c)

If this error is wanted at that stage (and not a bug in itself) I'd ask to maybe make it a warning or something similar as errors are always printed.

**Comment by kevinmehall** [comment]
https://github.com/kevinmehall/nusb/pull/40 lowers the log level to `debug!()` for all errors that occur in `list_devices`.

In your case the device is a SteelSeries audio device with a driver that wouldn't be usable with nusb anyway, so can be safely ignored. I don't necessarily want to filter out interfaces at enumeration based on driver, because many do have usable interface numbers, so we can tell whether something exists with the wrong driver vs doesn't exist at all. If it fails to parse the hardware ID like this, the interface will be ignored, so you'd want that in the debug log in case you were actually trying to use that device.
